#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

SERVICE_USE_PID=1

start () {
	exec 1>/dev/console  ;# redirect stdout to serial console
	exec 2>/dev/console  ;# redirect stderr to serial console

	echo "cron start()"

	loglevel=$(uci_get "system.@system[0].cronloglevel")
	[ -z "$(ls /etc/crontabs/)" ] && exit 1
	mkdir -p /var/spool/cron
	ln -s /etc/crontabs /var/spool/cron/ 2>/dev/null
	service_start /usr/sbin/crond -c /etc/crontabs -l ${loglevel:-5}

	echo "cron start() done"
}

stop() {
	service_stop /usr/sbin/crond
}
