FQDNLookup  false
BaseDir     "/var/lib/collectd"
PIDFile     "/var/run/collectd.pid"
Interval    30
ReadThreads 2

LoadPlugin cpu
LoadPlugin memory
LoadPlugin syslog
LoadPlugin write_graphite
LoadPlugin wireless
LoadPlugin interface
#LoadPlugin smaps

<Plugin syslog>
    LogLevel "info"
</Plugin>

<Plugin write_graphite>
    <Node "beep_collectd">
        Host "remix.beepdevices.com"
        Port "5141"
        Protocol "udp"
        LogSendErrors false
        Prefix "device."
    </Node>
</Plugin>

<Plugin interface>
    Interface "wlan0"
</Plugin>
#
#<Plugin smaps>
#    watch "beepjs"
#</Plugin>
