#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	exec 1>/dev/console  ;# redirect stdout to serial console
	exec 2>/dev/console  ;# redirect stderr to serial console

	echo "done files boot() "
	[ -d /tmp/root ] && {
		lock /tmp/.switch2jffs
		switch2jffs
		lock -u /tmp/.switch2jffs
	}

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done
	echo "done files boot() done"
}
