#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org 

START=11
start() {
	exec 1>/dev/console  ;# redirect stdout to serial console
	exec 2>/dev/console  ;# redirect stderr to serial console

	echo "sysctl start()"
	[ -f /etc/sysctl.conf ] && sysctl -p -e >&-
	echo "sysctl start() done"
}
