#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=98

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_PID_FILE=/var/run/sysntpd.pid

start() {
	exec 1>/dev/console  ;# redirect stdout to serial console
	exec 2>/dev/console  ;# redirect stderr to serial console

	echo "sysntpd start()"
	local peers
	local args="-n"
	local enable_server

	config_load system
	config_get peers ntp server
	config_get_bool enable_server ntp enable_server 0

	if [ $enable_server -ne 0 ]; then
		append args "-l"
	fi

	if [ -n "$peers" ]; then
		local peer
		for peer in $peers; do
			append args "-p $peer"
		done
	fi

	if [ "$args" != "-n" ]; then
		service_start /usr/sbin/ntpd $args
	fi
	echo "sysntpd start() done"
}

stop() {
	service_stop /usr/sbin/ntpd
}
