#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org 

START=39
start() {
	echo "start S39usb\n"
	[ -d /proc/bus/usb ] && {
		mount -o noatime -t usbfs none /proc/bus/usb
	}		
	echo "end S39usb\n"
}
