## This file contains files and directories that should
## be preserved during an upgrade.

# /etc/example.conf
# /etc/openvpn/
/etc/beep_tunnel_port

/etc/config/beep_data
/etc/config/beep_device
/etc/config/beep_devel

/etc/config/wireless
/etc/config/system

# Prevent serial console being disabled until a reboot.
/etc/inittab

# Keep drop bear host keys.
/etc/dropbear/dropbear_rsa_host_key
/etc/dropbear/dropbear_dss_host_key
