#include "beep_ubus.h"

const struct blobmsg_policy beep_state_policy[] = {
    POLICY(BEEP_STATE_STATE, "state", BLOBMSG_TYPE_TABLE),
    POLICY(BEEP_STATE_EVENT_TYPE, "event_type", BLOBMSG_TYPE_STRING),
    POLICY(BEEP_STATE_EVENT_DATA, "event_data", BLOBMSG_TYPE_TABLE),
};

const struct blobmsg_policy distributor_state_policy[] = {
    POLICY(DISTRIBUTOR_STATE_TRACK_ELAPSED_SECS, "track_elapsed_secs",
            BLOBMSG_TYPE_INT32),
    POLICY(DISTRIBUTOR_STATE_TOKEN, "token",
            BLOBMSG_TYPE_INT32),
    POLICY(DISTRIBUTOR_STATE_STREAMBUF_USED, "streambuf_used",
            BLOBMSG_TYPE_INT32),
    POLICY(DISTRIBUTOR_STATE_OUTPUT_USED, "output_used",
            BLOBMSG_TYPE_INT32),
    POLICY(DISTRIBUTOR_STATE_WRITTEN_TRACK_TIME, "written_track_time",
            BLOBMSG_TYPE_INT32),
    POLICY(DISTRIBUTOR_STATE_DURATION, "duration",
            BLOBMSG_TYPE_INT32),
    POLICY(DISTRIBUTOR_STATE_AUDIO_STATE, "audio_state", BLOBMSG_TYPE_STRING),
    POLICY(DISTRIBUTOR_STATE_PLAY_STATE, "play_state", BLOBMSG_TYPE_STRING),
    POLICY(DISTRIBUTOR_STATE_LOCAL_VOLUME, "local_volume", BLOBMSG_TYPE_INT32),
    POLICY(DISTRIBUTOR_STATE_MASTER_VOLUME, "master_volume", BLOBMSG_TYPE_INT32),
    POLICY(DISTRIBUTOR_STATE_STATION, "station", BLOBMSG_TYPE_TABLE),
    POLICY(DISTRIBUTOR_STATE_TRACK_INFO, "track_info", BLOBMSG_TYPE_ARRAY),
    POLICY(DISTRIBUTOR_STATE_PLAYERS, "players", BLOBMSG_TYPE_TABLE),
};

const struct blobmsg_policy playnet_state_policy[] = {
    POLICY(PLAYNET_STATE_NUM_TRACKS_STARTED, "num_tracks_started",
            BLOBMSG_TYPE_INT32),
    POLICY(PLAYNET_STATE_OUTPUT_USED, "output_used", BLOBMSG_TYPE_INT32),
    POLICY(PLAYNET_STATE_OUTPUT_SIZE, "output_size", BLOBMSG_TYPE_INT32),
    POLICY(PLAYNET_STATE_STREAMBUF_FREE, "streambuf_free", BLOBMSG_TYPE_INT32),
    POLICY(PLAYNET_STATE_CAN_ST_BEGIN, "can_st_begin", BLOBMSG_TYPE_BOOL),
    POLICY(PLAYNET_STATE_WRITTEN_TRACK_TIME, "written_track_time",
            BLOBMSG_TYPE_INT32),
    POLICY(PLAYNET_STATE_SYNC_PLAYED_TIME, "sync_played_time",
            BLOBMSG_TYPE_INT32),
    POLICY(PLAYNET_STATE_SYNC_TIMESTAMP, "sync_timestamp", BLOBMSG_TYPE_INT32),
    POLICY(PLAYNET_STATE_GAIN, "gain", BLOBMSG_TYPE_INT32),
};

const struct blobmsg_policy manager_state_policy[] = {
    POLICY(MANAGER_STATE_GROUPS, "groups", BLOBMSG_TYPE_TABLE),
    POLICY(MANAGER_STATE_LOCAL_DEVICE, "local_device", BLOBMSG_TYPE_TABLE),
    POLICY(MANAGER_STATE_DEVICES, "devices", BLOBMSG_TYPE_TABLE),
};

const struct blobmsg_policy manager_local_policy[] = {
    POLICY(MANAGER_LOCAL_SOURCE_ID,"source_id",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_LOCAL_SINK_ID,"sink_id",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_LOCAL_DEVICE_ID,"device_id",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_LOCAL_SIG_AVG,"sig_avg",BLOBMSG_TYPE_INT32),
    POLICY(MANAGER_LOCAL_NAME,"name",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_LOCAL_GROUP_LABEL,"group_label",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_LOCAL_SET_UUID,"set_uuid",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_LOCAL_APPS,"apps",BLOBMSG_TYPE_ARRAY),
    POLICY(MANAGER_LOCAL_SOURCE_TIME,"source_time",BLOBMSG_TYPE_INT32),
};

const struct blobmsg_policy manager_device_policy[] = {
    POLICY(MANAGER_DEVICE_SINK_ID,"sink_id",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_DEVICE_SOURCE_ID,"source_id",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_DEVICE_NAME,"name",BLOBMSG_TYPE_STRING),
    POLICY(MANAGER_DEVICE_PORT,"port",BLOBMSG_TYPE_INT32),
    POLICY(MANAGER_DEVICE_IP,"ip",BLOBMSG_TYPE_STRING),
};
