#include <stdint.h>

// Table 8-36 IEEE std 802.11-2012.
const char *beepnl_reasonstr(uint16_t reason) {
    switch (reason) {
    case 1: return "Unspecified reason";
    case 2: return "Previous authentication no longer valid";
    case 3: return "Deauthenticated because sending STA is leaving (or has left) IBSS or ESS";
    case 4: return "Disassociated due to inactivity";
    case 5: return "Disassociated because AP is unable to handle all currently associated STAs";
    case 6: return "Class 2 frame received from nonauthenticated STA";
    case 7: return "Class 3 frame received from nonassociated STA";
    case 8: return "Disassociated because sending STA is leaving (or has left) BSS";
    case 9: return "STA requesting (re)association is not authenticated with responding STA";
    case 10: return "Disassociated because the information in the Power Capability element is unacceptable";
    case 11: return "Disassociated because the information in the Supported Channels element is unacceptable";
    case 12: return "Disassociated due to BSS Transition Management";
    case 13: return "Invalid element, i.e., an element defined in this standard for which the content does not meet the specifications in Clause 8";
    case 14: return "Message integrity code (MIC) failure";
    case 15: return "4-Way Handshake timeout";
    case 16: return "Group Key Handshake timeout";
    case 17: return "element in 4-Way Handshake different from (Re)Association Request/Probe Response/Beacon frame";
    case 18: return "Invalid group cipher";
    case 19: return "Invalid pairwise cipher";
    case 20: return "Invalid AKMP";
    case 21: return "Unsupported RSNE version";
    case 22: return "Invalid RSNE capabilities";
    case 23: return "IEEE 802.1X authentication failed";
    case 24: return "Cipher suite rejected because of the security policy";
    case 25: return "TDLS direct-link teardown due to TDLS peer STA unreachable via the TDLS direct link";
    case 26: return "TDLS direct-link teardown for unspecified reason";
    case 27: return "Disassociated because session terminated by SSP request";
    case 28: return "Disassociated because of lack of SSP roaming agreement";
    case 29: return "Requested service rejected because of SSP cipher suite or AKM requirement";
    case 30: return "Requested service not authorized in this location";
    case 31: return "TS deleted because QoS AP lacks sufficient bandwidth for this QoS STA due to a change in BSS service characteristics or operational mode (e.g., an HT BSS change from 40 MHz channel to 20 MHz channel)";
    case 32: return "Disassociated for unspecified, QoS-related reason";
    case 33: return "Disassociated because QoS AP lacks sufficient bandwidth for this QoS STA";
    case 34: return "Disassociated because excessive number of frames need to be acknowledged, but are not acknowledged due to AP transmissions and/or poor channel conditions";
    case 35: return "Disassociated because STA is transmitting outside the limits of its TXOPs";
    case 36: return "Requested from peer STA as the STA is leaving the BSS (or resetting)";
    case 37: return "Requested from peer STA as it does not want to use the mechanism";
    case 38: return "Requested from peer STA as the STA received frames using the mechanism for which a setup is required";
    case 39: return "Requested from peer STA due to timeout";
    case 45: return "Peer STA does not support the requested cipher suite";
    case 46: return "DLS: The teardown was initiated by the DLS peer / DISASSOC: Disassociated because authorized access limit reached";
    case 47: return "DLS: The teardown was initiated by the / DISASSOC: Disassociated due to external service requirements";
    case 48: return "Invalid FT Action frame count";
    case 49: return "Invalid pairwise master key identifier (PMKI)";
    case 50: return "Invalid MDE";
    case 51: return "Invalid FTE";
    case 52: return "SME cancels the mesh peering instance with the reason other than reaching the maximum number of peer mesh STAs";
    case 53: return "The mesh STA has reached the supported maximum number of peer mesh STAs";
    case 54: return "The received information violates the Mesh Configuration policy configured in the mesh STA profile";
    case 55: return "The mesh STA has received a Mesh Peering Close message requesting to close the mesh peering";
    case 56: return "The mesh STA has resent dot11MeshMaxRetries Mesh Peering Open messages, without receiving a Mesh Peering Confirm message";
    case 57: return "The confirmTimer for the mesh peering instance times out";
    case 58: return "The mesh STA fails to unwrap the GTK or the values in the wrapped contents do not match";
    case 59: return "The mesh STA receives inconsistent information about the mesh parameters between Mesh Peering Management frames";
    case 60: return "The mesh STA fails the authenticated mesh peering exchange because due to failure in selecting either the pairwise ciphersuite or group ciphersuite";
    case 61: return "The mesh STA does not have proxy information for this external destination";
    case 62: return "The mesh STA does not have forwarding information for this destination";
    case 63: return "The mesh STA determines that the link to the next hop of an active path in its forwarding information is no longer usable";
    case 64: return "The Deauthentication frame was sent because the MAC address of the STA already exists in the mesh BSS";
    case 65: return "The mesh STA performs channel switch to meet regulatory requirements";
    case 66: return "The mesh STA performs channel switch with unspecified reason";
    default: return "Reserved";
    }
}

// Table 8-37 IEEE std 802.11-2012.
const char *beepnl_statusstr(uint16_t status) {
    switch (status) {
    case 0: return "Successful";
    case 1: return "Unspecified failure";
    case 2: return "TDLS wakeup schedule rejected but alternative schedule provided";
    case 3: return "TDLS wakeup schedule rejected";
    case 5: return "Security disabled";
    case 6: return "Unacceptable lifetime";
    case 7: return "Not in same BSS";
    case 10: return "Cannot support all requested capabilities in the Capability Information field";
    case 11: return "Reassociation denied due to inability to confirm that association exists";
    case 12: return "Association denied due to reason outside the scope of this standard";
    case 13: return "Responding STA does not support the specified authentication algorithm";
    case 14: return "Received an Authentication frame with authentication transaction sequence number out of expected sequence";
    case 15: return "Authentication rejected because of challenge failure";
    case 16: return "Authentication rejected due to timeout waiting for next frame in sequence";
    case 17: return "Association denied because AP is unable to handle additional associated STAs";
    case 18: return "Association denied due to requesting STA not supporting all of the data rates in the BSSBasicRateSet parameter";
    case 19: return "Association denied due to requesting STA not supporting the short preamble option";
    case 20: return "Association denied due to requesting STA not supporting the PBCC modulation option";
    case 21: return "Association denied due to requesting STA not supporting the Channel Agility option";
    case 22: return "Association request rejected because Spectrum Management capability is required";
    case 23: return "Association request rejected because the information in the Power Capability element is unacceptable";
    case 24: return "Association request rejected because the information in the Supported Channels element is unacceptable";
    case 25: return "Association denied due to requesting STA not supporting the Short Slot Time option";
    case 26: return "Association denied due to requesting STA not supporting the DSSS-OFDM option";
    case 27: return "Association denied because the requesting STA does not support HT features";
    case 28: return "R0KH unreachable";
    case 29: return "Association denied because the requesting STA does not support the phased coexistence operation (PCO) transition time required by the AP";
    case 30: return "Association request rejected temporarily; try again later";
    case 31: return "Robust management frame policy violation";
    case 32: return "Unspecified, QoS-related failure";
    case 33: return "Association denied because QoS AP has insufficient bandwidth to handle another QoS STA";
    case 34: return "Association denied due to excessive frame loss rates and/or poor conditions on current operating channel";
    case 35: return "Association (with QoS BSS) denied because the requesting STA does not support the QoS facility";
    case 37: return "The request has been declined";
    case 38: return "The request has not been successful as one or more parameters have invalid values";
    case 39: return "The TS has not been created because the request cannot be honored; however, a suggested TSPEC is provided so that the initiating STA may attempt to set another TS with the suggested changes to the TSPEC";
    case 40: return "Invalid element, i.e., an element defined in this standard for which the content does not meet the specifications in Clause 8";
    case 41: return "Invalid group cipher";
    case 42: return "Invalid pairwise cipher";
    case 43: return "Invalid AKMP";
    case 44: return "Unsupported RSNE version";
    case 45: return "Invalid RSNE capabilities";
    case 46: return "Cipher suite rejected because of security policy";
    case 47: return "The TS has not been created; however, the HC may be capable of creating a TS, in response to a request, after the time indicated in the TS Delay element";
    case 48: return "Direct link is not allowed in the BSS by policy";
    case 49: return "The Destination STA is not present within this BSS";
    case 50: return "The Destination STA is not a QoS STA";
    case 51: return "Association denied because the Listen Interval is too large";
    case 52: return "Invalid FT Action frame count";
    case 53: return "Invalid pairwise master key identifier (PMKID)";
    case 54: return "Invalid MDE";
    case 55: return "Invalid FTE";
    case 56: return "Requested TCLAS processing is not supported by the AP";
    case 57: return "The AP has insufficient TCLAS processing resources to satisfy the request";
    case 58: return "The TS has not been created because the request cannot be honored; however, the HC suggests the STA transitions to other BSSs to setup the TS";
    case 59: return "GAS Advertisement Protocol not supported";
    case 60: return "No outstanding GAS request";
    case 61: return "GAS Response not received from the Advertisement Server";
    case 62: return "STA timed out waiting for GAS Query Response";
    case 63: return "GAS Response is larger than query response length limit";
    case 64: return "Request refused because home network does not support request";
    case 65: return "Advertisement Server in the network is not currently reachable";
    case 67: return "Request refused due to permissions received via SSPN interface";
    case 68: return "Request refused because AP does not support unauthenticated access";
    case 72: return "Invalid contents of RSNE";
    case 73: return "U-APSD Coexistence is not supported";
    case 74: return "Requested U-APSD Coexistence mode is not supported";
    case 75: return "Requested Interval/Duration value cannot be supported with U-APSD Coexistence";
    case 76: return "Authentication is rejected because an Anti-Clogging Token is required";
    case 77: return "Authentication is rejected because the offered finite cyclic group is not supported";
    case 78: return "The TBTT adjustment request has not been successful because the STA could not find an alternative TBTT";
    case 79: return "Transmission failure";
    case 80: return "Requested TCLAS Not Supported";
    case 81: return "TCLAS Resources Exhausted";
    case 82: return "Rejected with Suggested BSS Transition";
    case 92: return "(Re)association refused for some external reason";
    case 93: return "(Re)association refused because of memory limits at the AP";
    case 94: return "(Re)association refused because emergency services are not supported at the AP";
    case 95: return "GAS query response not yet received";
    case 100: return "The request failed due to a reservation conflict";
    case 101: return "The request failed due to exceeded MAF limit";
    case 102: return "The request failed due to exceeded MCCA track limit";
    default: return "Reserved";
    }
}
