#ifndef IOMCU_BOOTLOADER_B3_MAIN_H
#define IOMCU_BOOTLOADER_B3_MAIN_H


#define BTLDR_DEV_INFO_BRD_ID                   (I2C_DEV_INFO_BRD_ID_DEMO_BOARD_1)
#define BTLDR_DEV_INFO_BRD_REV                  (1)
#define BTLDR_DEV_INFO_CHIP_ID                  (I2C_DEV_INFO_CHIP_ID_STM8L152C6)


#endif  // IOMCU_BOOTLOADER_B3_MAIN_H
