#!/bin/sh /etc/rc.common

START=12
# No STOP, this must always be running.

SERVICE_DAEMONIZE=1
SERVICE_MATCH_NAME=1
SERVICE_MATCH_EXEC=

start() {
	exec 1>/dev/console  ;# redirect stdout to serial console
	exec 2>/dev/console  ;# redirect stderr to serial console

	echo "start beepio"

	service_start /beep/beepio

	echo "start beepio done"
}

stop() {
    echo "stop beepio"
    service_stop /beep/beepio
}
