#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=97

start() {
	exec 1>/dev/console  ;# redirect stdout to serial console
	exec 2>/dev/console  ;# redirect stderr to serial console

	echo "watchdog start()"
	[ -c /dev/watchdog ] || return 1
	[ -x /sbin/watchdog ] || return 1
	service_start /sbin/watchdog -t 5 /dev/watchdog
	echo "watchdog start() done"
}
stop() {
	service_stop /sbin/watchdog
}
