#!/bin/sh /etc/rc.common

START=15
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	exec 1>/dev/console  ;# redirect stdout to serial console
	exec 2>/dev/console  ;# redirect stderr to serial console

	echo "Starting network start()\n"
	stop
	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	service_start /sbin/netifd

	setup_switch() { return 0; }
	
	include /lib/network
	setup_switch

	sleep 5

	/sbin/wifi down
	/sbin/wifi up
	echo "Ending network start()\n"
}

restart() {
	ifdown -a
	sleep 1
	#start
	stop
	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	service_start /sbin/netifd

	setup_switch() { return 0; }
	
	include /lib/network
	setup_switch

	sleep 5

	/sbin/wifi down
	/sbin/wifi up
	echo "Ending network start()\n"
}

shutdown() {
	ifdown -a
	stop
}

stop() {
	/sbin/wifi down
	service_stop /sbin/netifd
}

reload() {
	ubus call network reload
	/sbin/wifi down
	/sbin/wifi up
}
