### DO NOT EDIT -- AUTOMATICALLY GENERATED BY INIT.SH ###

import os, shutil, string, random
from beep.interface import DeviceTable as _DT, VirtualDevice as _VD
from string import ascii_uppercase

_BASE_DIR = os.path.split(__file__)[0]

with open(os.path.join(_BASE_DIR, '_beep_apps')) as _:
    _beep_apps_template = _.read()

with open(os.path.join(_BASE_DIR, '_beep_data')) as _:
    _beep_data_template = _.read()

with open(os.path.join(_BASE_DIR, '_beep_devel')) as _:
    _beep_devel_template = _.read()

with open(os.path.join(_BASE_DIR, '_beep_device')) as _:
    _beep_device_template = _.read()

with open(os.path.join(_BASE_DIR, '_beep_static')) as _:
    _beep_static_template = _.read()

dtab = _DT()

def generate_devices(unique_id=None,num=8):
    identifiers = ascii_uppercase[:num]
    index = 0

    if unique_id is None:
        chars = string.ascii_lowercase + string.digits
        unique_id = ''.join(random.choice(chars) for _ in xrange(5))

    dtab.clear()
    for identifier in ascii_uppercase:
        path = os.path.abspath(os.path.join(_BASE_DIR,identifier))
        if os.path.exists(path):
            shutil.rmtree(path)

    for identifier in identifiers:
        dev_id = '%s_%s' % (unique_id, identifier)
        path = os.path.abspath(os.path.join(_BASE_DIR,identifier))
        dtab[dev_id] = _VD('localhost:%s' % str(27200 + index), path)

        beep_apps = _beep_apps_template

        beep_data = _beep_data_template \
                .replace('$DEV_NAME','Automated Test Device %s' % identifier) \
                .replace('$GROUP_ID','1') \
                .replace('$CLUSTER_ID','test%s' % unique_id) \

        beep_devel = _beep_devel_template \
                .replace('$VERSION_PATH','/tmp/a1.version') \
                .replace('$URELAY_PORT',str(27000 + index)) \
                .replace('$PLAYNET_PORT',str(27100 + index)) \
                .replace('$UHTTPD_PORT',str(27200 + index)) \
                .replace('$SPOTIFY_PORT',str(27300 + index)) \
                .replace('$SSDP_PORT',str(27400 + index)) \
                .replace('$DIAL_PORT',str(27500 + index)) \
                .replace('$MSG_PORT',str(27600 + index))

        beep_device = _beep_device_template \
                .replace('$DEV_ID', dev_id) \

        beep_static = _beep_static_template

        if not os.path.exists(path):
            os.makedirs(path)

        with open('%s/beep_apps' % path, 'w') as beep_apps_file:
            beep_apps_file.write(beep_apps)

        with open('%s/beep_data' % path, 'w') as beep_data_file:
            beep_data_file.write(beep_data)

        with open('%s/beep_device' % path, 'w') as beep_device_file:
            beep_device_file.write(beep_device)

        with open('%s/beep_devel' % path, 'w') as beep_devel_file:
            beep_devel_file.write(beep_devel)

        with open('%s/beep_static' % path, 'w') as beep_static_file:
            beep_static_file.write(beep_static)

        index += 1

    return dtab
